-- QUESTÃO 01
CREATE TABLE best_films (id serial PRIMARY KEY, title varchar(200) NOT NULL, description TEXT NOT NULL);

-- QUESTÃO 02

-- QUESTÃO 03
INSERT INTO best_films (title, description) VALUES ($$Being the Ricardos$$, $$Writer/director Aaron Sorkin's biopic and show-biz drama, told through flashbacks and various witness-perspectives, followed the fame and fortunes of 1950s-TV most-beloved couple: RKO's red-headed studio actress Lucille Ball (Nicole Kidman) who had appeared in numerous low-budget films, and Cuban-born singer/band-leader Desi Arnaz (Javier Bardem). After marrying and moving to Hollywood, Lucy's casting in the successful radio show My Favorite Husband in 1948 morphed by 1953 into a very popular CBS-TV comedy sit-com show renamed I Love Lucy, where the two played husband and wife. Behind the scenes, the couple were already facing issues regarding Arnaz's frequent cheating and infidelity. On the set of I Love Lucy, Vivian Vance (Nina Arianda) and William Frawley (J.K. Simmons) (portraying their married neighbors Ethel and Fred Mertz), continually feuded with each other, and Frawley was frequently drunk. However, the hit TV show and their own marriage were even more threatened during a tumultuous week ( a period known as the Red Scare), when political allegations surfaced in a newspaper article - claiming that Lucy was a Communist. Although Lucy was cleared of the charges, their martial problems intensified and ultimately led to Lucy filing for divorce after the taping of their last show in 1960.$$);
INSERT INTO best_films (title, description) VALUES ($$Belfast$$,$$This semi-autobiographical, B/W political and childhood drama, written and directed by Kenneth Branagh, was set amidst the tumult and turmoil of life in Northern Ireland in the late 1960s, when conflict and problems in the region (known as "The Troubles") were occurring between "Protestants" (composed mostly of Unionists and Loyalists who wanted to remain united with the UK) and "Catholics" (composed mostly of Nationalists and Republicans who wanted a united Ireland). The main character was 9 year-old Irish boy named Buddy (Jude Hill), who had a brother named Will (Lewis McAskie). Buddy's grandparents were Granny (Judi Dench) and Pop (Ciarán Hinds). Buddy's working-class parents Pa and Ma (Jamie Dornan and Caitriona Balfe) were worried that their family was in extreme danger (and might be forced to move), especially since they identified as 'Protestants' and were being pressured to take sides.$$);
INSERT INTO best_films (title, description) VALUES ($$CODA$$, $$The title of writer/director Sian Heder's sweet, highly-emotional, coming-of-age family drama and musical was taken from the acronym CODA (meaning 'Child of Deaf Adult'). The Best Picture Oscar winner was remarkable for having in its cast a trio of hearing-challenged actors. The only non-hearing impaired individual in the family of deaf people living in Cape Ann's town of Gloucester, Mass. (who were engaged in the fishing sales business) was talented, teenaged, 17 year-old Ruby Rossi (Britisher Emilia Jones), an aspiring singer with plans to attend college at the highly-competitive Berklee College of Music if she could acquire a scholarship. By signing for her family's deaf members, her father Frank (Troy Kotsur) and mother Jackie (Marlee Matlin) and older disgruntled brother Leo (Daniel Durant), they had become almost totally-co-dependent and reliant upon her to communicate for them - jeopardizing her chances of an educational future. She was also struggling to have a normal romantic relationship with shy schoolmate Miles (Ferdia Walsh-Peelo), a member of the HS choir and her duet partner, while attending private singing lessons with her school's idealistic music teacher Bernardo "Mr. V” Villalobos (Eugenio Derbez) before auditioning for college. However, to fulfill her dreams, she realized that she would have to break away from her home and abandon her parents, who were pressuring her to continue as an intermediary involved in the family's fishing enterprise. She was resigned to her fate, until her parents attended her choir recital (and applauded when they saw others doing the same), and also secretly watched her Boston college audition from a balcony as she sang Joni Mitchell's 'Both Sides Now.' Remarkably, they remained supportive when she decided to follow her musical passion and proceed with her educational plans. In the film's ending, as Ruby was driven away, she flashed her family with one final ASL sign that meant: "I Love You" (the symbols of I, L, and Y).$$);
INSERT INTO best_films (title, description) VALUES ($$Don't Look Up$$, $$Writer/director Adam McKay's comedy about a possible, impending apocalyptic climate tragedy was prescient. Michigan State University Professor Dr. Randall Mindy (Leonardo DiCaprio) and his astronomy grad student Kate Dibiasky (Jennifer Lawrence) discovered a comet headed directly toward Earth that could potentially - in six months - destroy the entire planet. Their serious warnings during a whirlwind media tour fell on deaf ears and were met with apathy and indifference, from individuals including US President Janie Orlean (Meryl Streep), her Chief of Staff/son Jason (Jonah Hill) and two upbeat, popular morning talk show (The Daily Rip) hosts Brie Evantee (Cate Blanchett) and Jack (Tyler Perry). Individuals took sides over the issue - those who wished to save the planet with efforts to divert the comet, those who wanted to exploit the comet's valuable and scarce previous minerals (led by tech billionaire Peter Isherwell who was a prominent financial supporter of the President), and those who didn't believe that there was even a problem. The film concluded with a last-minute escape plan to avoid being obliterated - an exclusive flight on a spaceship to another Earth-like planet with passengers placed in cryogenic sleep. The comet struck Earth as predicted and killed nearly everyone (although there were some who survived, including Jason). During the end credits, 22,000 years into the future, the spaceship landed on a tropical alien planet where the survivors were immediately attacked and killed by wild animals.$$);
INSERT INTO best_films (title, description) VALUES ($$Drive My Car$$, $$Japanese director/writer Ryûsuke Hamaguchi's contemplative, heart-wrenching, lengthy psychological drama about grief was adapted from Haruki Murakami's 2014 short story. Nominated for both Best Picture and for Best International Feature Film. In the story, the recently widowed Yusuke Kafuku (Hidetoshi Nishijima), a famed and successful stage actor/director in Tokyo, had been chosen to direct a new adapted production in Hiroshima of Chekov's Russian play Uncle Vanya. Two years earlier, Yusuke's TV playwright wife Oto (Reika Kirishima) had suddenly and unexpectedly disappeared and was presumed dead. Soft-spoken, initially-intimidated young Misaki Watari (Toko Miura) served as Yusuke's chauffeur due to safety rules, and drove him to and from the production's many rehearsals. She was hired to drive him in his own beloved, red Saab 900 (hence the title "Drive My Car"). They bonded together as he began to be haunted by thoughts that his wife had betrayed him and been unfaithful with handsome TV star Koshi Takatsuki (Masaki Okada), whom he had inexplicably cast in the current production as the middle-aged Vanya.$$);
INSERT INTO best_films (title, description) VALUES ($$Dune$$,$$This was the second version of Frank Herbert’s popular and epic 1965 sci-fi novel (its first half), following director David Lynch's 1984 box-office failure. The big-budget, messianic hero's-journey tale (Part One) was set more than 8,000 years in the future. On the limited, foggy and misty oceanic planet of Caladan, gifted heir and son Paul Atreides (Timothée Chalamet) was born into the noble House of Atreides, consisting of Duke Leto Atreides (Oscar Isaac) and witch-mother concubine Lady Jessica Atreides (Rebecca Ferguson), a member of the sisterhood of Bene Gesserit. Troubled by premonitions and visions of the future (including a Fremen woman named Chani (Zendaya)), Paul was entrusted with traveling to Arrakis (aka Dune), a dangerous, inhospitable desert planet, to protect the future of his family and people. Arrakis was home to a very precious and valuable psychogenic substance known as "melange" (aka "the spice") - a drug that prolonged life and enhanced thinking and perception. The desert crop known as "spice" was also required for interstellar travel by navigators to instantly cover vast distances through expanded consciousness. Also on the planet were giant sandworms that traveled under the desert. Imperial politics were in full swing, as malevolent forces known as the Harkonnens had been fighting for many centuries over the drug with the planet's navite warrior-inhabitants, the Fremen. Deadly war was imminent in the future between the House of Atreides and their foes - the monstrous House of Harkonnen, once Paul arrived on Arrakis. In the film's conclusion, Paul joined the Fremen to fulfill his father's goal of bringing peace to Arrakis.$$);
INSERT INTO best_films (title, description) VALUES ($$The Eyes of Tammy Faye$$, $$$This biographical drama was based upon an earlier documentary film, The Eyes of Tammy Faye (2000), directed by Fenton Bailey and Randy Barbato, and narrated by drag queen RuPaul. In the 1960s in rural Minnesota, small-time country-girl Tammy Faye Grover (Jessica Chastain) with a strict religious upbringing, met up with fellow college student Jim Bakker (Andrew Garfield), a professed man of God. They married impulsively, and took their Christian message on the road, with programs showcasing Jim's preaching plus Tammy's singing. By the mid-1960s, they hosted a popular children's show, Jim and Tammy, and then hosted The 700 Club on Pat Robertson's Christian Broadcasting Network (CBN). Joined together as evangelists, they rose to fame through their inspirational and upbeat message of hope, love, and forgiveness. In the mid-1970s, they struck out on their own by establishing the world’s largest religious broadcasting network, the PTL (Praise the Lord) network, centered on their popular show The PTL Club (aka The Jim and Tammy Show) that lasted from 1974-1989. They also established a 2,500-acre mixed-use family Christian theme park and resort in Fort Mill, South Carolina, known as Heritage USA. However, their ostentatious and lucrative lifestyles (of lavishness and luxury, and Tammy's own problems with drug addiction) and emphasis on prosperity led to accusations of the misuse of financial funds, and Bakker was also charged with various sexual misconduct scandals and fraud. They lost control of their entire PTL empire when it collapsed by the late 1980s, and eventually divorced in 1994.$
INSET INTO best_films (title, description) VALUES ($$Licorice Pizza$$, $$The title of writer/director Paul Thomas Anderson's nostalgic, quirky coming-of-age romantic drama was derived from the name of a regional record store chain (now defunct) that was established in Southern California (San Fernando Valley) in the early 1970s, but was bought out by Sam Goody. [Note: Its initials LP stood for "Long Playing" - a reference to black vinyl records round-shaped like a pizza.] The events of the films were loosely based on the director's own youth in SoCal. The main story (about a first love) told of the budding relationship between two mismatched youths with clashing personalities separated by 10 years of age: 15 year-old opportunist, overconfident teen actor Gary Valentine (the late Philip Seymour Hoffman's 18 year-old son, Cooper Hoffman in his debut role), and 25-year-old Alana Kane (29 year-old Alana Haim also in her film debut - a musician in the female trio rock band Haim), a photographer's assistant. They first met during a yearbook picture-taking session at his HS (Grant), and afterwards, Gary's manager-mother Momma Anita (Mary Elizabeth Ellis) allowed Alana to chaperone him to NYC to attend a cast reunion for the family comedy-variety show "Under One Roof" (a stand-in for the film Yours, Mine, and Ours (1968)). In 1973, it was a time of the gas crisis, the 'waterbed' craze and legal prohibitions against pin-balling - facts worked into the film when budding, entrepreneurial hustler Gary attempted various business schemes. He started a waterbed company, partnered with Alana, and in a comic sequence, they delivered a waterbed to the home of crazed, womanizing hairdresser Jon Peters (Bradley Cooper) - a real-life Hollywood producer who was dating actress/singer Barbra Streisand. The waterbed destroyed the house during a disastrous installation. Gary also took advantage of the legalization of pinball in 1973 by opening a game arcade. Through many common scenarios and their tumultuous misadventures, they were increasingly drawn to each other and became soul-mated friends.$$);

-- QUESTÃO 04
select title from best_films where description like '%she%';
-- two rows returned

-- QUESTÃO 05
select title from best_films where description like '%She%';
-- two rows returned, but they are not the same items as the first select
-- The first select with 'she' returned 'CODA' and 'Don't Look Up'
-- The second select with 'She' returned 'CODA' and 'Drive My Car'

-- QUESTÃO 06
select title from best_films where description ilike '%she%';

-- QUESTÃO 07
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'directs');

-- QUESTÃO 08
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'direct');
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'directed');
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'director');
-- the first two queries returned the same result (‘Belfast’, 'Don't Look Up', 'Drive My Car'), but the third query returned only 'DUNE'

-- QUESTÃO 09
SELECT to_tsquery('english', 'directs');
SELECT to_tsquery('english', 'direct');
SELECT to_tsquery('english', 'directed');
SELECT to_tsquery('english', 'director');
-- direct, directs and directed are mapped to the same word (direct), whereas director is mapped to director.

-- QUESTÃO 10
SELECT title FROM best_films WHERE description LIKE '%drama%';
SELECT title FROM best_films WHERE description LIKE '%Drama%';
SELECT title FROM best_films WHERE description ILIKE '%drama%';

-- QUESTÃO 11
SELECT to_tsquery('english', 'directs');
SELECT to_tsquery('english', 'direct');
SELECT to_tsquery('english', 'directed');
SELECT to_tsquery('english', 'director');

-- QUESTÃO 12

-- QUESTÃO 13.a
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'drama | family');

-- QUESTÃO 13.b
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', 'drama | family');

-- QUESTÃO 13.c
SELECT title FROM best_films WHERE to_tsvector('english', description) @@ to_tsquery('english', '!drama');